# Generated by Django 4.2.5 on 2023-09-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_alter_user_signup_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=50)),
                ('Book_code', models.CharField(max_length=10)),
                ('Author_Name', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=50)),
                ('Book_Amount', models.IntegerField()),
                ('Created_Date', models.DateField()),
                ('Created_By', models.CharField(max_length=50)),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=50)),
            ],
        ),
    ]
