# Generated by Django 4.2.5 on 2023-09-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_book_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='Mob',
            field=models.BigIntegerField(),
        ),
    ]
