# Generated by Django 4.2.5 on 2023-09-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0006_alter_user_signup_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='Dob',
            field=models.CharField(max_length=30),
        ),
    ]
