# Generated by Django 4.2.5 on 2023-10-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_alter_user_signup_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='Dob',
            field=models.DateField(),
        ),
    ]
