# Generated by Django 4.2.5 on 2023-10-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0008_alter_user_signup_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
