# Generated by Django 4.2.5 on 2023-10-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0009_user_signup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_details',
            name='file_name',
            field=models.FileField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
