# Generated by Django 4.2.5 on 2023-10-09 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0010_book_details_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_details',
            old_name='file_name',
            new_name='Book_Img',
        ),
    ]
